theme: jekyll-theme-minimal
title: CRoute
description: CRoute adalah sebuah aplikasi desktop yang berfungsi membandingkan emisi yang dihasilkan dari perjalanan menggunakan berbagai kendaraan. Aplikasi ini diharapkan membantu pengguna dalam memilih moda transportasi yang lebih ramah lingkungan dengan menyajikan estimasi jumlah emisi yang dihasilkan dari setiap pilihan moda transportasi. selain itu aplikasi ini juga menyediakan informasi mengenai
